// hash: #ed854cf7
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtCastExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtCastExpressionBuilder
{
	var expression: KtExpression? = null
	
	var target: KtExpression? = null
	
	var isConditionalCast: Boolean? = null
	
	fun build(): KtCastExpression =
		DefaultKtCastExpression(
			expression!!,
			target!!,
			isConditionalCast!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
