// hash: #13c845d7
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtDirectGenericTypeArgument

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtDirectGenericTypeArgumentBuilder
{
	var typeReference: KtTypeReference? = null
	
	fun build(): KtDirectGenericTypeArgument =
		DefaultKtDirectGenericTypeArgument(
			typeReference!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
