// hash: #452989c8
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtFunction

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtFunctionBuilder
{
	var name: String? = null
	
	var parameters: MutableList<KtParameter>? = mutableListOf()
	
	var returnType: KtTypeReference? = null
	
	var body: MutableList<KtExpression>? = null
	
	var isOverride: Boolean? = null
	
	var isExpressionBody: Boolean? = null
	
	var visibility: KtVisibility? = null
	
	fun build(): KtFunction =
		DefaultKtFunction(
			name!!,
			parameters!!.toMutableList(),
			returnType,
			body?.toMutableList(),
			isOverride!!,
			isExpressionBody!!,
			visibility!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
