// hash: #1797817e
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtFunctionTypeReference

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtFunctionTypeReferenceBuilder
{
	var parameters: MutableList<KtTypeReference>? = mutableListOf()
	
	var result: KtTypeReference? = null
	
	var isNullable: Boolean? = null
	
	var scope: KtTypeReference? = null
	
	fun build(): KtFunctionTypeReference =
		DefaultKtFunctionTypeReference(
			parameters!!.toMutableList(),
			result!!,
			isNullable!!,
			scope,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
