// hash: #e0e52512
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtImport

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtImportBuilder
{
	var path: MutableList<String>? = mutableListOf()
	
	var isStarImport: Boolean? = null
	
	var alias: String? = null
	
	fun build(): KtImport =
		DefaultKtImport(
			path!!.toMutableList(),
			isStarImport!!,
			alias,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
