// hash: #d45af69c
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtInterface

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtInterfaceBuilder
{
	var name: String? = null
	
	var generics: MutableList<KtGenericTypeDeclaration>? = mutableListOf()
	
	var superTypes: MutableList<KtTypeReference>? = mutableListOf()
	
	var isSealed: Boolean? = null
	
	var visibility: KtVisibility? = null
	
	var members: MutableList<KtInterfaceMember>? = mutableListOf()
	
	fun build(): KtInterface =
		DefaultKtInterface(
			name!!,
			generics!!.toMutableList(),
			superTypes!!.toMutableList(),
			isSealed!!,
			visibility!!,
			members!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
