// hash: #c71d80ae
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtLambdaExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtLambdaExpressionBuilder
{
	var parameters: MutableList<KtParameter>? = mutableListOf()
	
	var body: MutableList<KtExpression>? = mutableListOf()
	
	fun build(): KtLambdaExpression =
		DefaultKtLambdaExpression(
			parameters!!.toMutableList(),
			body!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
