// hash: #eabc0d94
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtNameExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtNameExpressionBuilder
{
	var name: String? = null
	
	fun build(): KtNameExpression =
		DefaultKtNameExpression(
			name!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
