// hash: #58062b69
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtObject

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtObjectBuilder
{
	var name: String? = null
	
	var superTypes: MutableList<KtTypeReference>? = mutableListOf()
	
	var isCompanion: Boolean? = null
	
	var visibility: KtVisibility? = null
	
	var members: MutableList<KtObjectMember>? = mutableListOf()
	
	fun build(): KtObject =
		DefaultKtObject(
			name,
			superTypes!!.toMutableList(),
			isCompanion!!,
			visibility!!,
			members!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
