// hash: #343fee29
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtPropertyGetExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtPropertyGetExpressionBuilder
{
	var supplierExpression: KtExpression? = null
	
	var propertyName: String? = null
	
	fun build(): KtPropertyGetExpression =
		DefaultKtPropertyGetExpression(
			supplierExpression!!,
			propertyName!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
