// hash: #9db1b51c
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtRawCodeExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtRawCodeExpressionBuilder
{
	var code: String? = null
	
	fun build(): KtRawCodeExpression =
		DefaultKtRawCodeExpression(
			code!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
