// hash: #3d87c769
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtScript

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtScriptBuilder
{
	var name: String? = null
	
	var `package`: KtPackage? = null
	
	var imports: MutableList<KtImport>? = mutableListOf()
	
	var templatedValues: MutableList<KtTemplatedValue>? = mutableListOf()
	
	var members: MutableList<KtScriptMember>? = mutableListOf()
	
	var sourceFolder: String? = null
	
	fun build(): KtScript =
		DefaultKtScript(
			name!!,
			`package`,
			imports!!.toMutableList(),
			templatedValues!!.toMutableList(),
			members!!.toMutableList(),
			sourceFolder!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
