// hash: #f98c5f8a
// @formatter:off

package me.wietlol.tomplot.kotlin.data.builders

import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.DefaultKtTodoExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtTodoExpressionBuilder
{
	var text: String? = null
	
	fun build(): KtTodoExpression =
		DefaultKtTodoExpression(
			text,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
