// hash: #6b61fc93
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtCastExpression(
	override val expression: KtExpression,
	override val target: KtExpression,
	override val isConditionalCast: Boolean,
) : KtCastExpression
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtCastExpression =
		copy(
			expression = expression.duplicate(),
			target = target.duplicate(),
			isConditionalCast = isConditionalCast,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
