// hash: #7f99818b
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtLocalVariableDeclarationExpression(
	override val name: String,
	override val upperBound: KtTypeReference?,
	override val initialValue: KtExpression?,
	override val isVariable: Boolean,
) : KtLocalVariableDeclarationExpression
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtLocalVariableDeclarationExpression =
		copy(
			name = name,
			upperBound = upperBound?.duplicate(),
			initialValue = initialValue?.duplicate(),
			isVariable = isVariable,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
