// hash: #48305fa5
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtVisibility(
	override val code: String,
) : KtVisibility
{
	companion object
	{
		val `public`: DefaultKtVisibility = DefaultKtVisibility("public")
		
		val internal: DefaultKtVisibility = DefaultKtVisibility("internal")
		
		val `protected`: DefaultKtVisibility = DefaultKtVisibility("protected")
		
		val `private`: DefaultKtVisibility = DefaultKtVisibility("private")
	}
	
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtVisibility =
		copy(
			code = code,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
