// hash: #9879decc
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtScript(
	override val name: String,
	override val `package`: KtPackage?,
	override val imports: List<KtImport>,
	override val templatedValues: List<KtTemplatedValue>,
	override val members: List<KtScriptMember>,
	override val sourceFolder: String,
) : KtScript
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtScript =
		copy(
			name = name,
			`package` = `package`?.duplicate(),
			imports = imports.map { it.duplicate() }.toMutableList(),
			templatedValues = templatedValues.map { it.duplicate() }.toMutableList(),
			members = members.map { it.duplicate() }.toMutableList(),
			sourceFolder = sourceFolder,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
