// hash: #5f912269
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtGenericTypeDeclaration(
	override val name: String,
	override val variance: String?,
	override val superType: KtTypeReference?,
) : KtGenericTypeDeclaration
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtGenericTypeDeclaration =
		copy(
			name = name,
			variance = variance,
			superType = superType?.duplicate(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
