// hash: #a8f958f7
// data: serializationKey:7cb28642-cd33-4bc9-b979-7519821f7fd6
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtConstructorParameter : BitSerializable, KtElement, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("7cb28642-cd33-4bc9-b979-7519821f7fd6")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val upperBound: KtTypeReference
	
	val defaultValueExpression: KtExpression?
	
	val propertyType: KtPropertyType?
	
	val isOverride: Boolean
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtConstructorParameter) return false
		
		if (name != other.name) return false
		if (upperBound != other.upperBound) return false
		if (defaultValueExpression != other.defaultValueExpression) return false
		if (propertyType != other.propertyType) return false
		if (isOverride != other.isOverride) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(upperBound)
			.with(defaultValueExpression)
			.with(propertyType)
			.with(isOverride)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"upperBound":${upperBound.toJsonString()},"defaultValueExpression":${defaultValueExpression.toJsonString()},"propertyType":${propertyType.toJsonString()},"isOverride":${isOverride.toJsonString()}}"""
	
	override fun duplicate(): KtConstructorParameter
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
