// hash: #0a19ce38
// data: serializationKey:c175c530-5cd6-4fd4-88e7-34956463d81e
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtDirectGenericTypeArgument : BitSerializable, KtGenericTypeArgument, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("c175c530-5cd6-4fd4-88e7-34956463d81e")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val typeReference: KtTypeReference
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtDirectGenericTypeArgument) return false
		
		if (typeReference != other.typeReference) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(typeReference)
	
	override fun toJson(): String =
		"""{"typeReference":${typeReference.toJsonString()}}"""
	
	override fun duplicate(): KtDirectGenericTypeArgument
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
