// hash: #eff16649
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface KtGenericTypeArgument : BitSerializable, KtElement, Jsonable
{
	override fun duplicate(): KtGenericTypeArgument
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
