// hash: #87f88094
// data: serializationKey:a75b0183-2b09-4b0e-a95b-94da610ce4c4
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtIntegerLiteralExpression : BitSerializable, KtExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("a75b0183-2b09-4b0e-a95b-94da610ce4c4")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val value: Int
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtIntegerLiteralExpression) return false
		
		if (value != other.value) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(value)
	
	override fun toJson(): String =
		"""{"value":${value.toJsonString()}}"""
	
	override fun duplicate(): KtIntegerLiteralExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
