// hash: #e5119b57
// data: serializationKey:f43d06de-6e25-4fe3-abf2-d0692cca87a7
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtParameter : BitSerializable, KtElement, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("serializationKey")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val upperBound: KtTypeReference
	
	val defaultValueExpression: KtExpression?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtParameter) return false
		
		if (name != other.name) return false
		if (upperBound != other.upperBound) return false
		if (defaultValueExpression != other.defaultValueExpression) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(upperBound)
			.with(defaultValueExpression)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"upperBound":${upperBound.toJsonString()},"defaultValueExpression":${defaultValueExpression.toJsonString()}}"""
	
	override fun duplicate(): KtParameter
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
