// hash: #8643131b
// data: serializationKey:bf6b7e72-a397-4151-adc7-23604ce0619b
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtProperty : BitSerializable, KtComponent, KtInterfaceMember, KtObjectMember, KtClassMember, KtScriptMember, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("bf6b7e72-a397-4151-adc7-23604ce0619b")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val type: KtPropertyType
	
	val isOverride: Boolean
	
	val upperBound: KtTypeReference
	
	val getter: KtExpression?
	
	val visibility: KtVisibility
	
	val initialValue: KtExpression?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtProperty) return false
		
		if (name != other.name) return false
		if (type != other.type) return false
		if (isOverride != other.isOverride) return false
		if (upperBound != other.upperBound) return false
		if (getter != other.getter) return false
		if (visibility != other.visibility) return false
		if (initialValue != other.initialValue) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(type)
			.with(isOverride)
			.with(upperBound)
			.with(getter)
			.with(visibility)
			.with(initialValue)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"type":${type.toJsonString()},"isOverride":${isOverride.toJsonString()},"upperBound":${upperBound.toJsonString()},"getter":${getter.toJsonString()},"visibility":${visibility.toJsonString()},"initialValue":${initialValue.toJsonString()}}"""
	
	override fun duplicate(): KtProperty
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
