// hash: #3563ade9
// data: serializationKey:68bf2d25-53b0-4a9d-b736-40f694abf331
// @formatter:off

package me.wietlol.tomplot.kotlin.data.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtVisibility : BitSerializable, KtElement, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("68bf2d25-53b0-4a9d-b736-40f694abf331")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val code: String
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtVisibility) return false
		
		if (code != other.code) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(code)
	
	override fun toJson(): String =
		"""{"code":${code.toJsonString()}}"""
	
	override fun duplicate(): KtVisibility
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
