// hash: #e728dffa
// @formatter:off

package me.wietlol.tomplot.kotlin.data

import me.wietlol.bitblock.api.registry.ModelRegistry
import me.wietlol.bitblock.api.registry.ModelRegistryKey
import me.wietlol.bitblock.api.registry.RegistrySet
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.core.BitBlockBase
import me.wietlol.bitblock.core.registry.CommonModelRegistryKey
import me.wietlol.tomplot.kotlin.data.serializers.*

// Generated by BitBlock version 1.0.0

object TomplotKotlin : RegistrySet
{
	override val modelSerializers: Map<ModelRegistryKey, ModelSerializer<*, *>> = createModelSerializers()
	
	private fun createModelSerializers(): Map<ModelRegistryKey, ModelSerializer<*, *>> =
		mapOf(
			CommonModelRegistryKey("KtScript", "TomplotKotlin", "Wietlol", "1.0") to KtScriptSerializer,
			CommonModelRegistryKey("KtPackage", "TomplotKotlin", "Wietlol", "1.0") to KtPackageSerializer,
			CommonModelRegistryKey("KtImport", "TomplotKotlin", "Wietlol", "1.0") to KtImportSerializer,
			CommonModelRegistryKey("KtTemplatedValue", "TomplotKotlin", "Wietlol", "1.0") to KtTemplatedValueSerializer,
			CommonModelRegistryKey("KtComment", "TomplotKotlin", "Wietlol", "1.0") to KtCommentSerializer,
			CommonModelRegistryKey("KtCustomCode", "TomplotKotlin", "Wietlol", "1.0") to KtCustomCodeSerializer,
			CommonModelRegistryKey("KtFunction", "TomplotKotlin", "Wietlol", "1.0") to KtFunctionSerializer,
			CommonModelRegistryKey("KtInterface", "TomplotKotlin", "Wietlol", "1.0") to KtInterfaceSerializer,
			CommonModelRegistryKey("KtObject", "TomplotKotlin", "Wietlol", "1.0") to KtObjectSerializer,
			CommonModelRegistryKey("KtProperty", "TomplotKotlin", "Wietlol", "1.0") to KtPropertySerializer,
			CommonModelRegistryKey("KtParameter", "TomplotKotlin", "Wietlol", "1.0") to KtParameterSerializer,
			CommonModelRegistryKey("KtDirectTypeReference", "TomplotKotlin", "Wietlol", "1.0") to KtDirectTypeReferenceSerializer,
			CommonModelRegistryKey("KtFunctionTypeReference", "TomplotKotlin", "Wietlol", "1.0") to KtFunctionTypeReferenceSerializer,
			CommonModelRegistryKey("KtDirectGenericTypeArgument", "TomplotKotlin", "Wietlol", "1.0") to KtDirectGenericTypeArgumentSerializer,
			CommonModelRegistryKey("KtStarGenericTypeArgument", "TomplotKotlin", "Wietlol", "1.0") to KtStarGenericTypeArgumentSerializer,
			CommonModelRegistryKey("KtClass", "TomplotKotlin", "Wietlol", "1.0") to KtClassSerializer,
			CommonModelRegistryKey("KtConstructorParameter", "TomplotKotlin", "Wietlol", "1.0") to KtConstructorParameterSerializer,
			CommonModelRegistryKey("KtPropertyType", "TomplotKotlin", "Wietlol", "1.0") to KtPropertyTypeSerializer,
			CommonModelRegistryKey("KtVisibility", "TomplotKotlin", "Wietlol", "1.0") to KtVisibilitySerializer,
			CommonModelRegistryKey("KtGenericTypeDeclaration", "TomplotKotlin", "Wietlol", "1.0") to KtGenericTypeDeclarationSerializer,
			CommonModelRegistryKey("KtCastExpression", "TomplotKotlin", "Wietlol", "1.0") to KtCastExpressionSerializer,
			CommonModelRegistryKey("KtInvokeExpression", "TomplotKotlin", "Wietlol", "1.0") to KtInvokeExpressionSerializer,
			CommonModelRegistryKey("KtLocalVariableDeclarationExpression", "TomplotKotlin", "Wietlol", "1.0") to KtLocalVariableDeclarationExpressionSerializer,
			CommonModelRegistryKey("KtMemberAccessExpression", "TomplotKotlin", "Wietlol", "1.0") to KtMemberAccessExpressionSerializer,
			CommonModelRegistryKey("KtNameExpression", "TomplotKotlin", "Wietlol", "1.0") to KtNameExpressionSerializer,
			CommonModelRegistryKey("KtLambdaExpression", "TomplotKotlin", "Wietlol", "1.0") to KtLambdaExpressionSerializer,
			CommonModelRegistryKey("KtStringLiteralExpression", "TomplotKotlin", "Wietlol", "1.0") to KtStringLiteralExpressionSerializer,
			CommonModelRegistryKey("KtIntegerLiteralExpression", "TomplotKotlin", "Wietlol", "1.0") to KtIntegerLiteralExpressionSerializer,
			CommonModelRegistryKey("KtReturnExpression", "TomplotKotlin", "Wietlol", "1.0") to KtReturnExpressionSerializer,
			CommonModelRegistryKey("KtTodoExpression", "TomplotKotlin", "Wietlol", "1.0") to KtTodoExpressionSerializer,
			CommonModelRegistryKey("KtPropertyGetExpression", "TomplotKotlin", "Wietlol", "1.0") to KtPropertyGetExpressionSerializer,
			CommonModelRegistryKey("KtThisExpression", "TomplotKotlin", "Wietlol", "1.0") to KtThisExpressionSerializer,
			CommonModelRegistryKey("KtRawCodeExpression", "TomplotKotlin", "Wietlol", "1.0") to KtRawCodeExpressionSerializer,
		)
	
	override fun initialize(registry: ModelRegistry?) =
		modelSerializers.forEach((registry ?: BitBlockBase.modelRegistry)::set)
}
// @formatter:on
