// hash: #150fd0ea
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtClass

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtClassBuilder
{
	var name: String? = null
	
	var generics: MutableList<KtGenericTypeDeclaration>? = mutableListOf()
	
	var superTypes: MutableList<KtTypeReference>? = mutableListOf()
	
	var isDataClass: Boolean? = null
	
	var isValueClass: Boolean? = null
	
	var isSealed: Boolean? = null
	
	var primaryConstructorParameters: MutableList<KtConstructorParameter>? = mutableListOf()
	
	var visibility: KtVisibility? = null
	
	var members: MutableList<KtClassMember>? = mutableListOf()
	
	fun build(): KtClass =
		DefaultKtClass(
			name!!,
			generics!!.toMutableList(),
			superTypes!!.toMutableList(),
			isDataClass!!,
			isValueClass!!,
			isSealed!!,
			primaryConstructorParameters!!.toMutableList(),
			visibility!!,
			members!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
