// hash: #72a84ce7
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtDirectTypeReference

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtDirectTypeReferenceBuilder
{
	var path: MutableList<String>? = mutableListOf()
	
	var genericTypeArguments: MutableList<KtGenericTypeArgument>? = mutableListOf()
	
	var isNullable: Boolean? = null
	
	fun build(): KtDirectTypeReference =
		DefaultKtDirectTypeReference(
			path!!.toMutableList(),
			genericTypeArguments!!.toMutableList(),
			isNullable!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
