// hash: #ac7e4773
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtGenericTypeDeclaration

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtGenericTypeDeclarationBuilder
{
	var name: String? = null
	
	var variance: String? = null
	
	var superType: KtTypeReference? = null
	
	fun build(): KtGenericTypeDeclaration =
		DefaultKtGenericTypeDeclaration(
			name!!,
			variance,
			superType,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
