// hash: #e788f24a
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtIntegerLiteralExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtIntegerLiteralExpressionBuilder
{
	var value: Int? = null
	
	fun build(): KtIntegerLiteralExpression =
		DefaultKtIntegerLiteralExpression(
			value!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
