// hash: #c33bdd5b
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtProperty

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtPropertyBuilder
{
	var name: String? = null
	
	var type: KtPropertyType? = null
	
	var isOverride: Boolean? = null
	
	var upperBound: KtTypeReference? = null
	
	var getter: KtExpression? = null
	
	var visibility: KtVisibility? = null
	
	var initialValue: KtExpression? = null
	
	fun build(): KtProperty =
		DefaultKtProperty(
			name!!,
			type!!,
			isOverride!!,
			upperBound!!,
			getter,
			visibility!!,
			initialValue,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
