// hash: #880e2784
// @formatter:off

package tomplot.kotlin.data.builders

import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.DefaultKtStringLiteralExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class KtStringLiteralExpressionBuilder
{
	var value: String? = null
	
	var isTripleQuoted: Boolean? = null
	
	fun build(): KtStringLiteralExpression =
		DefaultKtStringLiteralExpression(
			value!!,
			isTripleQuoted!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
