// hash: #3b0d1af5
// @formatter:off

package tomplot.kotlin.data.builders

// Generated by BitBlock version 1.0.0

object TomplotKotlinBuilderFacade
{
	fun buildKtScript(body: KtScriptBuilder.() -> Unit) =
		KtScriptBuilder()
			.apply(body)
			.build()
	
	fun buildKtPackage(body: KtPackageBuilder.() -> Unit) =
		KtPackageBuilder()
			.apply(body)
			.build()
	
	fun buildKtImport(body: KtImportBuilder.() -> Unit) =
		KtImportBuilder()
			.apply(body)
			.build()
	
	fun buildKtTemplatedValue(body: KtTemplatedValueBuilder.() -> Unit) =
		KtTemplatedValueBuilder()
			.apply(body)
			.build()
	
	fun buildKtComment(body: KtCommentBuilder.() -> Unit) =
		KtCommentBuilder()
			.apply(body)
			.build()
	
	fun buildKtCustomCode(body: KtCustomCodeBuilder.() -> Unit) =
		KtCustomCodeBuilder()
			.apply(body)
			.build()
	
	fun buildKtFunction(body: KtFunctionBuilder.() -> Unit) =
		KtFunctionBuilder()
			.apply(body)
			.build()
	
	fun buildKtInterface(body: KtInterfaceBuilder.() -> Unit) =
		KtInterfaceBuilder()
			.apply(body)
			.build()
	
	fun buildKtObject(body: KtObjectBuilder.() -> Unit) =
		KtObjectBuilder()
			.apply(body)
			.build()
	
	fun buildKtProperty(body: KtPropertyBuilder.() -> Unit) =
		KtPropertyBuilder()
			.apply(body)
			.build()
	
	fun buildKtParameter(body: KtParameterBuilder.() -> Unit) =
		KtParameterBuilder()
			.apply(body)
			.build()
	
	fun buildKtDirectTypeReference(body: KtDirectTypeReferenceBuilder.() -> Unit) =
		KtDirectTypeReferenceBuilder()
			.apply(body)
			.build()
	
	fun buildKtFunctionTypeReference(body: KtFunctionTypeReferenceBuilder.() -> Unit) =
		KtFunctionTypeReferenceBuilder()
			.apply(body)
			.build()
	
	fun buildKtDirectGenericTypeArgument(body: KtDirectGenericTypeArgumentBuilder.() -> Unit) =
		KtDirectGenericTypeArgumentBuilder()
			.apply(body)
			.build()
	
	fun buildKtStarGenericTypeArgument(body: KtStarGenericTypeArgumentBuilder.() -> Unit) =
		KtStarGenericTypeArgumentBuilder()
			.apply(body)
			.build()
	
	fun buildKtClass(body: KtClassBuilder.() -> Unit) =
		KtClassBuilder()
			.apply(body)
			.build()
	
	fun buildKtConstructorParameter(body: KtConstructorParameterBuilder.() -> Unit) =
		KtConstructorParameterBuilder()
			.apply(body)
			.build()
	
	fun buildKtPropertyType(body: KtPropertyTypeBuilder.() -> Unit) =
		KtPropertyTypeBuilder()
			.apply(body)
			.build()
	
	fun buildKtVisibility(body: KtVisibilityBuilder.() -> Unit) =
		KtVisibilityBuilder()
			.apply(body)
			.build()
	
	fun buildKtGenericTypeDeclaration(body: KtGenericTypeDeclarationBuilder.() -> Unit) =
		KtGenericTypeDeclarationBuilder()
			.apply(body)
			.build()
	
	fun buildKtCastExpression(body: KtCastExpressionBuilder.() -> Unit) =
		KtCastExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtInvokeExpression(body: KtInvokeExpressionBuilder.() -> Unit) =
		KtInvokeExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtLocalVariableDeclarationExpression(body: KtLocalVariableDeclarationExpressionBuilder.() -> Unit) =
		KtLocalVariableDeclarationExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtMemberAccessExpression(body: KtMemberAccessExpressionBuilder.() -> Unit) =
		KtMemberAccessExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtNameExpression(body: KtNameExpressionBuilder.() -> Unit) =
		KtNameExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtLambdaExpression(body: KtLambdaExpressionBuilder.() -> Unit) =
		KtLambdaExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtStringLiteralExpression(body: KtStringLiteralExpressionBuilder.() -> Unit) =
		KtStringLiteralExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtIntegerLiteralExpression(body: KtIntegerLiteralExpressionBuilder.() -> Unit) =
		KtIntegerLiteralExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtReturnExpression(body: KtReturnExpressionBuilder.() -> Unit) =
		KtReturnExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtTodoExpression(body: KtTodoExpressionBuilder.() -> Unit) =
		KtTodoExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtPropertyGetExpression(body: KtPropertyGetExpressionBuilder.() -> Unit) =
		KtPropertyGetExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtThisExpression(body: KtThisExpressionBuilder.() -> Unit) =
		KtThisExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildKtRawCodeExpression(body: KtRawCodeExpressionBuilder.() -> Unit) =
		KtRawCodeExpressionBuilder()
			.apply(body)
			.build()
}
// @formatter:on
