// hash: #bcf64231
// @formatter:off

package tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import tomplot.kotlin.data.builders.KtConstructorParameterBuilder
import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.KtConstructorParameter
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtConstructorParameterSerializer : ModelSerializer<KtConstructorParameter, KtConstructorParameter>
{
	private val endOfObject: Int = 0
	
	private val nameIndex: Int = 1
	
	private val upperBoundIndex: Int = 2
	
	private val defaultValueExpressionIndex: Int = 3
	
	private val propertyTypeIndex: Int = 4
	
	private val isOverrideIndex: Int = 5
	
	override val modelId: UUID
		get() = KtConstructorParameter.serializationKey
	
	override val dataClass: Class<KtConstructorParameter>
		get() = KtConstructorParameter::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtConstructorParameter)
	{
		stream.writeUnsignedVarInt(nameIndex)
		schema.serialize(serializationContext, stream, entity.name)
		
		stream.writeUnsignedVarInt(upperBoundIndex)
		schema.serialize(serializationContext, stream, entity.upperBound)
		
		entity.defaultValueExpression?.also {
			stream.writeUnsignedVarInt(defaultValueExpressionIndex)
			schema.serialize(serializationContext, stream, it)
		}
		
		entity.propertyType?.also {
			stream.writeUnsignedVarInt(propertyTypeIndex)
			schema.serialize(serializationContext, stream, it)
		}
		
		stream.writeUnsignedVarInt(isOverrideIndex)
		schema.serialize(serializationContext, stream, entity.isOverride)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtConstructorParameter
	{
		var name: String? = null
		var upperBound: KtTypeReference? = null
		var defaultValueExpression: KtExpression? = null
		var propertyType: KtPropertyType? = null
		var isOverride: Boolean? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtConstructorParameter(
					name!!,
					upperBound!!,
					defaultValueExpression,
					propertyType,
					isOverride!!,
				)
				nameIndex -> name = schema.deserialize(deserializationContext, stream)
				upperBoundIndex -> upperBound = schema.deserialize(deserializationContext, stream)
				defaultValueExpressionIndex -> defaultValueExpression = schema.deserialize(deserializationContext, stream)
				propertyTypeIndex -> propertyType = schema.deserialize(deserializationContext, stream)
				isOverrideIndex -> isOverride = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
