// hash: #8261365c
// @formatter:off

package tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import tomplot.kotlin.data.builders.KtLambdaExpressionBuilder
import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.KtLambdaExpression
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtLambdaExpressionSerializer : ModelSerializer<KtLambdaExpression, KtLambdaExpression>
{
	private val endOfObject: Int = 0
	
	private val parametersIndex: Int = 1
	
	private val bodyIndex: Int = 2
	
	override val modelId: UUID
		get() = KtLambdaExpression.serializationKey
	
	override val dataClass: Class<KtLambdaExpression>
		get() = KtLambdaExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtLambdaExpression)
	{
		stream.writeUnsignedVarInt(parametersIndex)
		schema.serialize(serializationContext, stream, entity.parameters)
		
		stream.writeUnsignedVarInt(bodyIndex)
		schema.serialize(serializationContext, stream, entity.body)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtLambdaExpression
	{
		var parameters: MutableList<KtParameter>? = mutableListOf()
		var body: MutableList<KtExpression>? = mutableListOf()
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtLambdaExpression(
					parameters!!.toMutableList(),
					body!!.toMutableList(),
				)
				parametersIndex -> parameters = schema.deserialize(deserializationContext, stream)
				bodyIndex -> body = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
