// hash: #c05fb7e7
// @formatter:off

package tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import tomplot.kotlin.data.builders.KtRawCodeExpressionBuilder
import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.KtRawCodeExpression
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtRawCodeExpressionSerializer : ModelSerializer<KtRawCodeExpression, KtRawCodeExpression>
{
	private val endOfObject: Int = 0
	
	private val codeIndex: Int = 1
	
	override val modelId: UUID
		get() = KtRawCodeExpression.serializationKey
	
	override val dataClass: Class<KtRawCodeExpression>
		get() = KtRawCodeExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtRawCodeExpression)
	{
		stream.writeUnsignedVarInt(codeIndex)
		schema.serialize(serializationContext, stream, entity.code)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtRawCodeExpression
	{
		var code: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtRawCodeExpression(
					code!!,
				)
				codeIndex -> code = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
