// hash: #b480b947
// @formatter:off

package tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import tomplot.kotlin.data.builders.KtThisExpressionBuilder
import tomplot.kotlin.data.models.*
import tomplot.kotlin.data.models.KtThisExpression
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtThisExpressionSerializer : ModelSerializer<KtThisExpression, KtThisExpression>
{
	private val endOfObject: Int = 0
	
	private val scopeNameIndex: Int = 1
	
	override val modelId: UUID
		get() = KtThisExpression.serializationKey
	
	override val dataClass: Class<KtThisExpression>
		get() = KtThisExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtThisExpression)
	{
		entity.scopeName?.also {
			stream.writeUnsignedVarInt(scopeNameIndex)
			schema.serialize(serializationContext, stream, it)
		}
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtThisExpression
	{
		var scopeName: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtThisExpression(
					scopeName,
				)
				scopeNameIndex -> scopeName = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
