// hash: #d82f8242
// @formatter:off

package tomplot.xml.data.builders

import tomplot.xml.data.models.*
import tomplot.xml.data.models.DefaultXmlComment

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class XmlCommentBuilder
{
	var text: String? = null
	
	fun build(): XmlComment =
		DefaultXmlComment(
			text!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
