// hash: #51d4225a
// @formatter:off

package tomplot.xml.data.models

import bitblock.api.serialization.BitSerializable
import tomplot.api.data.TomplotElement
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface XmlElement : BitSerializable, TomplotElement, Jsonable
{
	override fun duplicate(): XmlElement
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
