// hash: #896c6413
// @formatter:off

package tomplot.xml.data.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface XmlNodeElement : BitSerializable, XmlElement, Jsonable
{
	override fun duplicate(): XmlNodeElement
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
