// hash: #ef191b25
// data: serializationKey:0057c7db-8c9a-42e0-9ef5-53031dc1484d
// @formatter:off

package tomplot.xml.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface XmlProlog : BitSerializable, XmlHeader, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("0057c7db-8c9a-42e0-9ef5-53031dc1484d")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val attributes: XmlAttributeSet
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is XmlProlog) return false
		
		if (name != other.name) return false
		if (attributes != other.attributes) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(attributes)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"attributes":${attributes.toJsonString()}}"""
	
	override fun duplicate(): XmlProlog
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
