// hash: #23be3e1e
// @formatter:off

package tomplot.kotlin.data.models

import tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtClass(
	override val name: String,
	override val generics: List<KtGenericTypeDeclaration>,
	override val superTypes: List<KtTypeReference>,
	override val isDataClass: Boolean,
	override val isValueClass: Boolean,
	override val isSealed: Boolean,
	override val primaryConstructorParameters: List<KtConstructorParameter>,
	override val visibility: KtVisibility,
	override val members: List<KtClassMember>,
) : KtClass
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtClass =
		copy(
			name = name,
			generics = generics.map { it.duplicate() }.toMutableList(),
			superTypes = superTypes.map { it.duplicate() }.toMutableList(),
			isDataClass = isDataClass,
			isValueClass = isValueClass,
			isSealed = isSealed,
			primaryConstructorParameters = primaryConstructorParameters.map { it.duplicate() }.toMutableList(),
			visibility = visibility.duplicate(),
			members = members.map { it.duplicate() }.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
