// hash: #e6915988
// @formatter:off

package tomplot.kotlin.data.models

import tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtFunctionTypeReference(
	override val parameters: List<KtTypeReference>,
	override val result: KtTypeReference,
	override val isNullable: Boolean,
	override val scope: KtTypeReference?,
) : KtFunctionTypeReference
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtFunctionTypeReference =
		copy(
			parameters = parameters.map { it.duplicate() }.toMutableList(),
			result = result.duplicate(),
			isNullable = isNullable,
			scope = scope?.duplicate(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
