// hash: #4bf839ef
// @formatter:off

package tomplot.kotlin.data.models

import tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtFunction(
	override val name: String,
	override val parameters: List<KtParameter>,
	override val returnType: KtTypeReference?,
	override val body: List<KtExpression>?,
	override val isOverride: Boolean,
	override val isExpressionBody: Boolean,
	override val visibility: KtVisibility,
) : KtFunction
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtFunction =
		copy(
			name = name,
			parameters = parameters.map { it.duplicate() }.toMutableList(),
			returnType = returnType?.duplicate(),
			body = body?.map { it.duplicate() }?.toMutableList(),
			isOverride = isOverride,
			isExpressionBody = isExpressionBody,
			visibility = visibility.duplicate(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
