// hash: #f6de46d3
// @formatter:off

package tomplot.kotlin.data.models

import tomplot.kotlin.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultKtMemberAccessExpression(
	override val supplier: KtExpression,
	override val memberName: String,
	override val isConditionalAccess: Boolean,
	override val isReferencingAccess: Boolean,
) : KtMemberAccessExpression
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultKtMemberAccessExpression =
		copy(
			supplier = supplier.duplicate(),
			memberName = memberName,
			isConditionalAccess = isConditionalAccess,
			isReferencingAccess = isReferencingAccess,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
