// hash: #c2a3fa41
// data: serializationKey:c55399f7-24b7-46f9-9812-16a25cef4837
// @formatter:off

package tomplot.kotlin.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtCustomCode : BitSerializable, KtInterfaceMember, KtObjectMember, KtClassMember, KtScriptMember, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("c55399f7-24b7-46f9-9812-16a25cef4837")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val id: String
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtCustomCode) return false
		
		if (id != other.id) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(id)
	
	override fun toJson(): String =
		"""{"id":${id.toJsonString()}}"""
	
	override fun duplicate(): KtCustomCode
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
