// hash: #63854fb3
// data: serializationKey:ef98c9ad-39a8-4f9d-8fcd-12e0107b0923
// @formatter:off

package tomplot.kotlin.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtGenericTypeDeclaration : BitSerializable, KtElement, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("ef98c9ad-39a8-4f9d-8fcd-12e0107b0923")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val variance: String?
	
	val superType: KtTypeReference?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtGenericTypeDeclaration) return false
		
		if (name != other.name) return false
		if (variance != other.variance) return false
		if (superType != other.superType) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(variance)
			.with(superType)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"variance":${variance.toJsonString()},"superType":${superType.toJsonString()}}"""
	
	override fun duplicate(): KtGenericTypeDeclaration
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
