// hash: #dc953869
// data: serializationKey:5085712c-0b25-4cae-886c-602cb5709867
// @formatter:off

package tomplot.kotlin.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtLambdaExpression : BitSerializable, KtExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("5085712c-0b25-4cae-886c-602cb5709867")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val parameters: List<KtParameter>
	
	val body: List<KtExpression>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtLambdaExpression) return false
		
		if (parameters != other.parameters) return false
		if (body != other.body) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(parameters)
			.with(body)
	
	override fun toJson(): String =
		"""{"parameters":${parameters.toJsonString()},"body":${body.toJsonString()}}"""
	
	override fun duplicate(): KtLambdaExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
