// hash: #3134041a
// data: serializationKey:58bd304b-d4ef-4a87-8360-c10c404cb8ea
// @formatter:off

package tomplot.kotlin.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtReturnExpression : BitSerializable, KtExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("58bd304b-d4ef-4a87-8360-c10c404cb8ea")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val value: KtExpression?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtReturnExpression) return false
		
		if (value != other.value) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(value)
	
	override fun toJson(): String =
		"""{"value":${value.toJsonString()}}"""
	
	override fun duplicate(): KtReturnExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
