// hash: #4d95ca3d
// @formatter:off

package tomplot.kotlin.data.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface KtScriptMember : BitSerializable, KtElement, Jsonable
{
	override fun duplicate(): KtScriptMember
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
