// hash: #04773c82
// data: serializationKey:0031a3f5-830a-403f-bee4-fa2237d4993c
// @formatter:off

package tomplot.kotlin.data.models

import java.util.UUID
import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface KtTemplatedValue : BitSerializable, KtElement, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("0031a3f5-830a-403f-bee4-fa2237d4993c")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val key: String
	
	val valueProvider: KtValueProvider
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is KtTemplatedValue) return false
		
		if (key != other.key) return false
		if (valueProvider != other.valueProvider) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(key)
			.with(valueProvider)
	
	override fun toJson(): String =
		"""{"key":${key.toJsonString()},"valueProvider":${valueProvider.toJsonString()}}"""
	
	override fun duplicate(): KtTemplatedValue
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
