// hash: #316db624
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtDirectTypeReferenceBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtDirectTypeReference
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtDirectTypeReferenceSerializer : ModelSerializer<KtDirectTypeReference, KtDirectTypeReference>
{
	private val endOfObject: Int = 0
	
	private val pathIndex: Int = 1
	
	private val genericTypeArgumentsIndex: Int = 2
	
	private val isNullableIndex: Int = 3
	
	override val modelId: UUID
		get() = KtDirectTypeReference.serializationKey
	
	override val dataClass: Class<KtDirectTypeReference>
		get() = KtDirectTypeReference::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtDirectTypeReference)
	{
		stream.writeUnsignedVarInt(pathIndex)
		schema.serialize(serializationContext, stream, entity.path)
		
		stream.writeUnsignedVarInt(genericTypeArgumentsIndex)
		schema.serialize(serializationContext, stream, entity.genericTypeArguments)
		
		stream.writeUnsignedVarInt(isNullableIndex)
		schema.serialize(serializationContext, stream, entity.isNullable)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtDirectTypeReference
	{
		var path: MutableList<String>? = mutableListOf()
		var genericTypeArguments: MutableList<KtGenericTypeArgument>? = mutableListOf()
		var isNullable: Boolean? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtDirectTypeReference(
					path!!.toMutableList(),
					genericTypeArguments!!.toMutableList(),
					isNullable!!,
				)
				pathIndex -> path = schema.deserialize(deserializationContext, stream)
				genericTypeArgumentsIndex -> genericTypeArguments = schema.deserialize(deserializationContext, stream)
				isNullableIndex -> isNullable = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
