// hash: #3f78e5a0
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtDirectGenericTypeArgumentBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtDirectGenericTypeArgument
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtDirectGenericTypeArgumentSerializer : ModelSerializer<KtDirectGenericTypeArgument, KtDirectGenericTypeArgument>
{
	private val endOfObject: Int = 0
	
	private val typeReferenceIndex: Int = 1
	
	override val modelId: UUID
		get() = KtDirectGenericTypeArgument.serializationKey
	
	override val dataClass: Class<KtDirectGenericTypeArgument>
		get() = KtDirectGenericTypeArgument::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtDirectGenericTypeArgument)
	{
		stream.writeUnsignedVarInt(typeReferenceIndex)
		schema.serialize(serializationContext, stream, entity.typeReference)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtDirectGenericTypeArgument
	{
		var typeReference: KtTypeReference? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtDirectGenericTypeArgument(
					typeReference!!,
				)
				typeReferenceIndex -> typeReference = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
