// hash: #c4f1f71e
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtImportBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtImport
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtImportSerializer : ModelSerializer<KtImport, KtImport>
{
	private val endOfObject: Int = 0
	
	private val pathIndex: Int = 1
	
	private val isStarImportIndex: Int = 2
	
	private val aliasIndex: Int = 3
	
	override val modelId: UUID
		get() = KtImport.serializationKey
	
	override val dataClass: Class<KtImport>
		get() = KtImport::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtImport)
	{
		stream.writeUnsignedVarInt(pathIndex)
		schema.serialize(serializationContext, stream, entity.path)
		
		stream.writeUnsignedVarInt(isStarImportIndex)
		schema.serialize(serializationContext, stream, entity.isStarImport)
		
		entity.alias?.also {
			stream.writeUnsignedVarInt(aliasIndex)
			schema.serialize(serializationContext, stream, it)
		}
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtImport
	{
		var path: MutableList<String>? = mutableListOf()
		var isStarImport: Boolean? = null
		var alias: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtImport(
					path!!.toMutableList(),
					isStarImport!!,
					alias,
				)
				pathIndex -> path = schema.deserialize(deserializationContext, stream)
				isStarImportIndex -> isStarImport = schema.deserialize(deserializationContext, stream)
				aliasIndex -> alias = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
