// hash: #2484d453
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtInvokeExpressionBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtInvokeExpression
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtInvokeExpressionSerializer : ModelSerializer<KtInvokeExpression, KtInvokeExpression>
{
	private val endOfObject: Int = 0
	
	private val functionIndex: Int = 1
	
	private val argumentsIndex: Int = 2
	
	override val modelId: UUID
		get() = KtInvokeExpression.serializationKey
	
	override val dataClass: Class<KtInvokeExpression>
		get() = KtInvokeExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtInvokeExpression)
	{
		stream.writeUnsignedVarInt(functionIndex)
		schema.serialize(serializationContext, stream, entity.function)
		
		stream.writeUnsignedVarInt(argumentsIndex)
		schema.serialize(serializationContext, stream, entity.arguments)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtInvokeExpression
	{
		var function: KtExpression? = null
		var arguments: MutableList<KtExpression>? = mutableListOf()
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtInvokeExpression(
					function!!,
					arguments!!.toMutableList(),
				)
				functionIndex -> function = schema.deserialize(deserializationContext, stream)
				argumentsIndex -> arguments = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
