// hash: #be2b462a
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtParameterBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtParameter
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtParameterSerializer : ModelSerializer<KtParameter, KtParameter>
{
	private val endOfObject: Int = 0
	
	private val nameIndex: Int = 1
	
	private val upperBoundIndex: Int = 2
	
	private val defaultValueExpressionIndex: Int = 3
	
	override val modelId: UUID
		get() = KtParameter.serializationKey
	
	override val dataClass: Class<KtParameter>
		get() = KtParameter::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtParameter)
	{
		stream.writeUnsignedVarInt(nameIndex)
		schema.serialize(serializationContext, stream, entity.name)
		
		stream.writeUnsignedVarInt(upperBoundIndex)
		schema.serialize(serializationContext, stream, entity.upperBound)
		
		entity.defaultValueExpression?.also {
			stream.writeUnsignedVarInt(defaultValueExpressionIndex)
			schema.serialize(serializationContext, stream, it)
		}
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtParameter
	{
		var name: String? = null
		var upperBound: KtTypeReference? = null
		var defaultValueExpression: KtExpression? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtParameter(
					name!!,
					upperBound!!,
					defaultValueExpression,
				)
				nameIndex -> name = schema.deserialize(deserializationContext, stream)
				upperBoundIndex -> upperBound = schema.deserialize(deserializationContext, stream)
				defaultValueExpressionIndex -> defaultValueExpression = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
