// hash: #14b01df7
// @formatter:off

package me.wietlol.tomplot.kotlin.data.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.tomplot.kotlin.data.builders.KtPropertyGetExpressionBuilder
import me.wietlol.tomplot.kotlin.data.models.*
import me.wietlol.tomplot.kotlin.data.models.KtPropertyGetExpression
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object KtPropertyGetExpressionSerializer : ModelSerializer<KtPropertyGetExpression, KtPropertyGetExpression>
{
	private val endOfObject: Int = 0
	
	private val supplierExpressionIndex: Int = 1
	
	private val propertyNameIndex: Int = 2
	
	override val modelId: UUID
		get() = KtPropertyGetExpression.serializationKey
	
	override val dataClass: Class<KtPropertyGetExpression>
		get() = KtPropertyGetExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: KtPropertyGetExpression)
	{
		stream.writeUnsignedVarInt(supplierExpressionIndex)
		schema.serialize(serializationContext, stream, entity.supplierExpression)
		
		stream.writeUnsignedVarInt(propertyNameIndex)
		schema.serialize(serializationContext, stream, entity.propertyName)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): KtPropertyGetExpression
	{
		var supplierExpression: KtExpression? = null
		var propertyName: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultKtPropertyGetExpression(
					supplierExpression!!,
					propertyName!!,
				)
				supplierExpressionIndex -> supplierExpression = schema.deserialize(deserializationContext, stream)
				propertyNameIndex -> propertyName = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
